CREATE INDEX TESTS_IDX
  ON TESTS (TEST_ID, THEME_ID)
  COMPUTE STATISTICS;

CREATE INDEX QUESTIONS_IDX
  ON QUESTIONS_FOR_TESTS (QUESTION_ID, TEST_ID)
  COMPUTE STATISTICS;
  
CREATE INDEX ANSWERS_IDX
  ON answers_for_tests (ANSWER_ID, QUESTION_ID)
  COMPUTE STATISTICS;
  
CREATE INDEX USER_ANSWERS_IDX
  ON USER_ANSWERS (QUESTION_ID, USER_ANSWER)
  COMPUTE STATISTICS;