alter session set current_schema = BLUEFOX_USER; 
alter session set current_schema = BLUEFOX_ADMIN; 

CREATE ROLE RL_BLUEFOX_USER;

GRANT CREATE SESSION, 
      SELECT ANY TABLE,
      UPDATE ANY TABLE,
      EXECUTE ANY PROCEDURE,
      create procedure to RL_BLUEFOX_USER;
      
CREATE USER BLUEFOX_USER IDENTIFIED BY oracle;

GRANT RL_BLUEFOX_USER TO BLUEFOX_USER;
      
--DROP USER BLUEFOX_USER;

CREATE OR REPLACE VIEW USERS_VIEW AS SELECT * FROM BLUEFOX_ADMIN.USERS;
CREATE OR REPLACE VIEW STATS_VIEW AS SELECT * FROM BLUEFOX_ADMIN.USER_STATS;
CREATE OR REPLACE VIEW INFO_VIEW AS SELECT * FROM BLUEFOX_ADMIN.USER_INFO;
CREATE OR REPLACE VIEW THEMES_VIEW AS SELECT * FROM BLUEFOX_ADMIN.THEMES_FOR_TESTS;
CREATE OR REPLACE VIEW TESTS_VIEW AS SELECT * FROM BLUEFOX_ADMIN.TESTS;
CREATE OR REPLACE VIEW QUESTIONS_VIEW AS SELECT * FROM BLUEFOX_ADMIN.QUESTIONS_FOR_TESTS;
CREATE OR REPLACE VIEW ANSWERS_VIEW AS SELECT * FROM BLUEFOX_ADMIN.ANSWERS_FOR_TESTS;
CREATE OR REPLACE VIEW TEST_RESULT_VIEW AS SELECT * FROM BLUEFOX_ADMIN.TEST_RESULT;
CREATE OR REPLACE VIEW USER_ANSWERS_VIEW AS SELECT * FROM BLUEFOX_ADMIN.USER_ANSWERS;


create synonym GET_THEMES for BLUEFOX_ADMIN.GET_THEMES;
create synonym ADD_USER_ANSWER for BLUEFOX_ADMIN.ADD_USER_ANSWER;
create synonym GET_THEME_BY_NAME for BLUEFOX_ADMIN.GET_THEME_BY_NAME;
create synonym GET_TESTS_BY_THEME_ID for BLUEFOX_ADMIN.GET_TESTS_BY_THEME_ID;
create synonym GET_QUESTIONS_BY_TEST_ID for BLUEFOX_ADMIN.GET_QUESTIONS_BY_TEST_ID;
create synonym GET_ANSWERS_BY_QUESTION_ID for BLUEFOX_ADMIN.GET_ANSWERS_BY_QUESTION_ID;
create synonym GET_USER_ANSWERS_BY_RESULT_ID for GET_USER_ANSWERS_BY_RESULT_ID.GET_TEST_BY_NAME;
create synonym FIND_TEST_RESULT for BLUEFOX_ADMIN.FIND_TEST_RESULT;
create synonym GET_TEST_RESULT_BY_RESULT_ID for BLUEFOX_ADMIN.GET_TEST_RESULT_BY_RESULT_ID;
create synonym GET_TEST_RESULTS_BY_USER_ID for BLUEFOX_ADMIN.GET_TEST_RESULTS_BY_USER_ID;
create synonym GET_USER_INFO for BLUEFOX_ADMIN.GET_USER_INFO;
create synonym GET_USER_STATS for BLUEFOX_ADMIN.GET_USER_STATS;
create synonym FUNC_INITIALIZE_TEST_RESULT for BLUEFOX_ADMIN.FUNC_INITIALIZE_TEST_RESULT;
create synonym UPDATE_USER_INFO for BLUEFOX_ADMIN.UPDATE_USER_INFO;
create synonym UPDATE_TEST_RESULT_TEST_END for BLUEFOX_ADMIN.UPDATE_TEST_RESULT_TEST_END;